// src/constants/entityConstants.js
export const FETCH_ENTITIES_REQUEST = 'FETCH_ENTITIES_REQUEST';
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIES_FAIL = 'FETCH_ENTITIES_FAIL';

export const FETCH_ENTITY_REQUEST = 'FETCH_ENTITY_REQUEST';
export const FETCH_ENTITY_SUCCESS = 'FETCH_ENTITY_SUCCESS';
export const FETCH_ENTITY_FAIL = 'FETCH_ENTITY_FAIL';

export const UPDATE_ENTITY_REQUEST = 'UPDATE_ENTITY_REQUEST';
export const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS';
export const UPDATE_ENTITY_FAIL = 'UPDATE_ENTITY_FAIL';

export const DELETE_ENTITY_REQUEST = 'DELETE_ENTITY_REQUEST';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAIL = 'DELETE_ENTITY_FAIL';

export const FETCH_CUISINES_REQUEST = 'FETCH_CUISINES_REQUEST'; // New
export const FETCH_CUISINES_SUCCESS = 'FETCH_CUISINES_SUCCESS'; // New
export const FETCH_CUISINES_FAIL = 'FETCH_CUISINES_FAIL';

export const UPDATE_CUISINE_REQUEST = 'UPDATE_CUISINE_REQUEST'; // New
export const UPDATE_CUISINE_SUCCESS = 'UPDATE_CUISINE_SUCCESS'; // New
export const UPDATE_CUISINE_FAIL = 'UPDATE_CUISINE_FAIL'; // New
export const DELETE_CUISINE_REQUEST = 'DELETE_CUISINE_REQUEST'; // New
export const DELETE_CUISINE_SUCCESS = 'DELETE_CUISINE_SUCCESS'; // New
export const DELETE_CUISINE_FAIL = 'DELETE_CUISINE_FAIL';

export const CREATE_CUISINE_REQUEST = 'CREATE_CUISINE_REQUEST'; // New
export const CREATE_CUISINE_SUCCESS = 'CREATE_CUISINE_SUCCESS'; // New
export const CREATE_CUISINE_FAIL = 'CREATE_CUISINE_FAIL';

export const CLEAR_ENTITIES = 'CLEAR_ENTITIES';

export const CLEAR_CIRCUIT_ENTITIES = 'CLEAR_CIRCUIT_ENTITIES';
