
  export const FETCH_GUEST_HOUSES_LOADING = 'FETCH_GUEST_HOUSES_LOADING';
  export const FETCH_GUEST_HOUSES_SUCCESS = 'FETCH_GUEST_HOUSES_SUCCESS';
  export const FETCH_GUEST_HOUSES_ERROR = 'FETCH_GUEST_HOUSES_ERROR';