export const SAVE_SEARCH_REQUEST = 'SAVE_SEARCH_REQUEST';
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';
export const SAVE_SEARCH_FAIL = 'SAVE_SEARCH_FAIL';

export const TRACK_CLICK_REQUEST = 'TRACK_CLICK_REQUEST';
export const TRACK_CLICK_SUCCESS = 'TRACK_CLICK_SUCCESS';
export const TRACK_CLICK_FAIL = 'TRACK_CLICK_FAIL';