# Generated by Django 5.1.7 on 2025-03-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destination',
            table='tourism.destination',
        ),
    ]
