# Generated by Django 5.1.7 on 2025-03-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_destination_id_alter_destination_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'managed': False},
        ),
    ]
