# Generated by Django 5.1.7 on 2025-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_destination_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destination',
            table='destination',
        ),
    ]
