# Generated by Django 5.1.7 on 2025-03-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
