# Generated by Django 5.1.7 on 2025-03-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
