# Generated by Django 5.1.7 on 2025-03-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': False},
        ),
    ]
