# Generated by Django 5.1.7 on 2025-03-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='tourism.restaurant',
        ),
    ]
