# Generated by Django 5.1.7 on 2025-03-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_alter_restaurant_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
