# Generated by Django 5.1.7 on 2025-03-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
